theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "eth0"
interval = 60

[[block]]
block = "net"
device = "eth1"
interval = 60

[[block]]
block = "custom"
command = "curl ifconfig.me"
json = false
interval = 1000
on_click = "curl ifconfig.me | wl-copy -p"

[[block]]
block = "custom"
command = '''echo "✓" (watson status)'''
json = false
interval = 30
hide_when_empty	= true
on_click = "watson stop"


[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5
on_click = "pactl set-sink-mute '@DEFAULT_SINK@' toggle"
device_kind = "sink"
#[block.mappings]
#"alsa_output.pci-0000_10_00.4.analog-stereo" = "🔈"
#"bluez_output.00_16_94_23_07_11.a2dp-sink" = "🎧"

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5
on_click = "pactl set-source-mute '@DEFAULT_SOURCE@' toggle"
device_kind = "source"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
timezone = "US/Eastern"
locale = "en_US"
on_click = "date +%Y-%m-%d | wl-copy -p"
