#! /bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load profiles from /etc/profile.d
if test -d /etc/profile.d/; then
        for profile in /etc/profile.d/*.sh; do
                test -r "$profile" && . "$profile"
        done
        for profile in /etc/profile.d/*.bash; do
                test -r "$profile" && . "$profile"
        done
        unset profile
fi

# Set initial PS1
PS1='[\u@\h \W]\$ '

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace
#HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

#append timestamp to bash_history
HISTTIMEFORMAT="%F %T "

# aggregate all commands executed
# PROMPT_COMMAND='history -n;history -a'
PROMPT_COMMAND='history -a'

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=
HISTFILESIZE=

# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias pgrep='pgrep -l'
alias termsize='echo $COLUMNS x $LINES'
alias dmesg='dmesg -T'
alias rm='rm -I'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
fi

# Tab complete ssh
#if [ -f ~/.ssh/config ];then
#    complete -o default -W "`grep -iE "\bhost\b" ~/.ssh/config | awk '{print $2 \" \" $3 \" \" $4 \" \" $5}'`" ssh scp sftp
#fi

#http://seejeffrun.blogspot.com/2008/08/error-handling-again.html
warn() { printf "$* at line %s file %s: $msg\n" "$(caller)" 1>&2 ; }
die() { printf "$* at line %s file %s: $msg\n" "$(caller)" 1>&2 ; exit -1; }

if [ -f /usr/bin/ruby ];then
    export PATH=$PATH:$(ruby -r rubygems -e "puts Gem.user_dir")/bin
fi

export EDITOR=vim
export VISUAL=vim

if [ -f /usr/bin/archey3 ];then
    timeout 1 archey3
fi

if [ -d $HOME/.bash-completion.d/ ];then
    for i in $HOME/.bash-completion.d/*;do source $i;done
fi

#http://superuser.com/questions/249293/rename-tmux-window-name-to-prompt-command-ps1-or-remote-ssh-hostname
settitle() {
  printf "\033k$1\033\\"
}
ssh() {
  settitle "$*"
  command ssh "$@"
  settitle "bash"
}
mosh() {
  settitle "$*"
  command mosh "$@"
  settitle "bash"
}

#. /usr/share/fzf/key-bindings.bash
#. /usr/share/fzf/completion.bash

# Set terminal title to $PWD
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

POWERLINE_BASH_CONFIG=$(find /usr/lib/python3*/site-packages/powerline/bindings/bash/ -name powerline.sh 2> /dev/null)

if [ -f $(which starship)  ];then
  eval "$(starship init bash)"
elif [ -f  "$POWERLINE_BASH_CONFIG"  ];then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . "$POWERLINE_BASH_CONFIG"
else
    export PS1="\u@\h:\w\\$ "
fi

export NODE_PATH="/usr/lib/node_modules"

# https://github.com/dschep/ntfy
if [ -f /usr/bin/ntfy ];then
    eval "$(ntfy shell-integration)"
    export AUTO_NTFY_DONE_IGNORE="vim screen meld"
fi
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    xhost +si:localuser:root &> /dev/null
fi

if [ -f /usr/bin/kubectl ];then
    source <(kubectl completion bash)
fi

# add node_modules to path
export PATH=$HOME/node_modules/.bin:$PATH

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

eval $(thefuck --alias)

# source FASD
source <(fasd --init auto)
# _fasd_bash_hook_cmd_complete v m j o

# Tab complete ssh
complete -o default -W "`grep -iE "\bhost\b" ~/.ssh/config | awk '{print $2 \" \" $3 \" \" $4 \" \" $5}'`" ssh scp sftp

# add user base to python path
export PYTHONPATH=$(python3 -c "import site, os; print(os.path.join(site.USER_BASE, 'lib', 'python', 'site-packages'))"):$PYTHONPATH

# add .local/bin to path
export PATH=~/.local/bin:$PATH

# rust
#. <(rustup completions bash cargo)
#. <(rustup completions bash rustup)
export PATH=$HOME/.cargo/bin:$PATH

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# asdf
if [ -f $HOME/.asdf/asdf.sh ]; then
  . $HOME/.asdf/asdf.sh
  . $HOME/.asdf/completions/asdf.bash
fi
. $(brew --prefix asdf)/libexec/asdf.sh
. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash
