complete -c rtw -n "__fish_use_subcommand" -s d -l dir -d 'storage directory'
complete -c rtw -n "__fish_use_subcommand" -l default -d 'use default config'
complete -c rtw -n "__fish_use_subcommand" -l overlap -d 'allow overlapping activities'
complete -c rtw -n "__fish_use_subcommand" -l no_overlap -d 'disallow overlapping activities'
complete -c rtw -n "__fish_use_subcommand" -s n -l dry -d 'dry run: don\'t write anything to the filesystem'
complete -c rtw -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_use_subcommand" -f -a "start" -d 'Start new activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "track" -d 'Track a finished activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "stop" -d 'Stop activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "summary" -d 'Display finished activities'
complete -c rtw -n "__fish_use_subcommand" -f -a "dump" -d 'Dump finished activities to stdout in iCalendar format'
complete -c rtw -n "__fish_use_subcommand" -f -a "continue" -d 'Continue a finished activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "day" -d 'Display the current day as a timeline'
complete -c rtw -n "__fish_use_subcommand" -f -a "week" -d 'Display the current week as a timeline'
complete -c rtw -n "__fish_use_subcommand" -f -a "timeline" -d 'Display finished activities as a timeline'
complete -c rtw -n "__fish_use_subcommand" -f -a "delete" -d 'Delete activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "cancel" -d 'cancel current activity'
complete -c rtw -n "__fish_use_subcommand" -f -a "completion" -d 'generate completion file'
complete -c rtw -n "__fish_use_subcommand" -f -a "status" -d 'print status data, suitable for use in status bar or prompts'
complete -c rtw -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c rtw -n "__fish_seen_subcommand_from start" -s d -l description -d 'long activity description'
complete -c rtw -n "__fish_seen_subcommand_from start" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from start" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from track" -s d -l description -d 'long activity description'
complete -c rtw -n "__fish_seen_subcommand_from track" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from track" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from stop" -l id -d 'optional activity id
current activity is stopped when omitted'
complete -c rtw -n "__fish_seen_subcommand_from stop" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from stop" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from summary" -l yesterday -d 'activities done yesterday'
complete -c rtw -n "__fish_seen_subcommand_from summary" -l lastweek -d 'activities done last week'
complete -c rtw -n "__fish_seen_subcommand_from summary" -l week -d 'activities done this week'
complete -c rtw -n "__fish_seen_subcommand_from summary" -l id -d 'display activities id'
complete -c rtw -n "__fish_seen_subcommand_from summary" -s d -l description -d 'display activities descriptions'
complete -c rtw -n "__fish_seen_subcommand_from summary" -s r -l report -d 'sum up activities with same tag together'
complete -c rtw -n "__fish_seen_subcommand_from summary" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from summary" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from dump" -l yesterday -d 'activities done yesterday'
complete -c rtw -n "__fish_seen_subcommand_from dump" -l lastweek -d 'activities done last week'
complete -c rtw -n "__fish_seen_subcommand_from dump" -l week -d 'activities done this week'
complete -c rtw -n "__fish_seen_subcommand_from dump" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from dump" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from continue" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from continue" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from day" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from day" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from week" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from week" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from timeline" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from timeline" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from cancel" -l id -d 'optional activity id
current activity is stopped when omitted'
complete -c rtw -n "__fish_seen_subcommand_from cancel" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from cancel" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from status" -l format -d 'format string e.g. "{id} {ongoing} {start} {human_duration} {duration}"'
complete -c rtw -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c rtw -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c rtw -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
