[theme]
file = "/home/dpendolino/.local/share/i3status-rust/themes/dracula.toml"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 200
warning = 20.0
alert = 10.0
format = "{icon} {path} {used}/{total}"

[[block]]
block = "memory"
display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"
interval = 30

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "load"
interval = 30
format = "{1m}"

[[block]]
block = "temperature"
collapsed = true
interval = 30
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "net"
device = "wlan0"
interval = 60

[[block]]
block = "custom"
command = "curl ifconfig.me"
json = false
interval = 1000
on_click = "curl ifconfig.me | wl-copy -p"

# [[block]]
# block = "custom"
# command = '''echo "✓" (rtw --format "{ongoing} {human_duration}")'''
# json = false
# interval = 3
# hide_when_empty	= true
# on_click = "rtw stop"


[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5
on_click = "pactl set-sink-mute '@DEFAULT_SINK@' toggle"
device_kind = "sink"
#[block.mappings]
#"alsa_output.pci-0000_10_00.4.analog-stereo" = "🔈"
#"bluez_output.00_16_94_23_07_11.a2dp-sink" = "🎧"

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5
on_click = "pactl set-source-mute '@DEFAULT_SOURCE@' toggle"
device_kind = "source"


[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
timezone = "US/Eastern"
locale = "en_US"
on_click = "date +%Y-%m-%d | wl-copy -p"
