SSOConfig:
    IbottaSSO:
        SSORegion: us-east-1
        StartUrl: https://d-90679808ff.awsapps.com/start
        DefaultRegion: us-east-1
        maxbackoff: 5
        maxretry: 10
DefaultSSO: IbottaSSO
DefaultRegion: us-east-1
ConsoleDuration: 60
CacheRefresh: 168
Threads: 5
MaxBackoff: 5
MaxRetry: 10
AutoConfigCheck: true
UrlAction: open-url-in-container
ConfigProfilesUrlAction: open-url-in-container
UrlExecCommand:
    - /opt/homebrew/bin/firefox
    - "%s"
LogLevel: error
HistoryLimit: 25
HistoryMinutes: 1440
#ProfileFormat: "{{.AccountAlias}:{{.RoleName}}"
ProfileFormat: "{{ nospace .AccountAlias }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountIdPad
    - AccountAlias
    - RoleName
    - Profile
    - Expires
FullTextSearch: true
