#!/usr/bin/env bash

killall polybar
#polybar example -r &
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    # MONITOR=$m polybar --reload example &
    MONITOR=$m polybar --reload main &
    MONITOR=$m polybar --reload bottom &
  done
else
  # polybar --reload example &
  polybar --reload main &
  polybar --reload bottom &
fi
